#!/bin/bash

# Shared validation and canonical rendering contract for RhwpCoreBuildInfo.swift.

rhwp_build_info_validate_release_tag() {
  local lock_file="$1"
  local key="$2"
  local value="$3"
  if ! [[ "$value" =~ ^[A-Za-z0-9][A-Za-z0-9._+/:~-]*$ ]]; then
    echo "ERROR: invalid $key in $lock_file: $value" >&2
    return 1
  fi
}

rhwp_build_info_validate_commit() {
  local lock_file="$1"
  local value="$2"
  if ! [[ "$value" =~ ^[0-9a-f]{40}$ ]]; then
    echo "ERROR: invalid rhwp_commit in $lock_file: $value" >&2
    return 1
  fi
}

rhwp_build_info_validate_enabled_features() {
  local lock_file="$1"
  local value="$2"
  if [ -n "$value" ] && ! [[ "$value" =~ ^[A-Za-z0-9_-]+(,[A-Za-z0-9_-]+)*$ ]]; then
    echo "ERROR: invalid rhwp_enabled_features in $lock_file: $value" >&2
    return 1
  fi
}

rhwp_build_info_load_lock() {
  local lock_file="$1"
  local read_lock="$2"
  local lock_version
  local ref_kind

  lock_version="$("$read_lock" --lock-file "$lock_file" lock_version)" || return $?
  if [ "$lock_version" != "2" ]; then
    echo "ERROR: unsupported rhwp-core.lock version: ${lock_version:-missing}" >&2
    echo "Expected: 2" >&2
    return 1
  fi

  ref_kind="$("$read_lock" --lock-file "$lock_file" rhwp_ref_kind)" || return $?
  case "$ref_kind" in
    release-tag)
      RHWP_BUILD_INFO_RELEASE_TAG_KEY="rhwp_release_tag"
      ;;
    commit)
      RHWP_BUILD_INFO_RELEASE_TAG_KEY="rhwp_latest_checked_release_tag"
      ;;
    *)
      echo "ERROR: unsupported rhwp_ref_kind in $lock_file: $ref_kind" >&2
      return 1
      ;;
  esac

  RHWP_BUILD_INFO_RELEASE_TAG="$(
    "$read_lock" --lock-file "$lock_file" "$RHWP_BUILD_INFO_RELEASE_TAG_KEY"
  )" || return $?
  RHWP_BUILD_INFO_COMMIT="$(
    "$read_lock" --lock-file "$lock_file" rhwp_commit
  )" || return $?
  RHWP_BUILD_INFO_ENABLED_FEATURES="$(
    "$read_lock" --lock-file "$lock_file" rhwp_enabled_features
  )" || return $?

  rhwp_build_info_validate_release_tag \
    "$lock_file" "$RHWP_BUILD_INFO_RELEASE_TAG_KEY" "$RHWP_BUILD_INFO_RELEASE_TAG" || return $?
  rhwp_build_info_validate_commit \
    "$lock_file" "$RHWP_BUILD_INFO_COMMIT" || return $?
  rhwp_build_info_validate_enabled_features \
    "$lock_file" "$RHWP_BUILD_INFO_ENABLED_FEATURES" || return $?
}

rhwp_build_info_render_swift() {
  printf '%s\n' \
    '// Generated by scripts/update-rhwp-core-build-info.sh. Do not edit manually.' \
    'enum RhwpCoreBuildInfo {' \
    "    static let releaseTag = \"$RHWP_BUILD_INFO_RELEASE_TAG\"" \
    "    static let commit = \"$RHWP_BUILD_INFO_COMMIT\"" \
    "    static let enabledFeatures = \"$RHWP_BUILD_INFO_ENABLED_FEATURES\"" \
    '}'
}
