// Generated by scripts/update-rhwp-core-build-info.sh. Do not edit manually.
enum RhwpCoreBuildInfo {
    static let releaseTag = "v0.8.4"
    static let commit = "496333b27d21ddb9114ba9ae340bcb895870c9a7"
    static let enabledFeatures = "native-skia"
}
