// Generated by scripts/update-rhwp-core-build-info.sh. Do not edit manually.
enum RhwpCoreBuildInfo {
    static let releaseTag = "v0.8.6"
    static let commit = "f1f9c6ae58344ee9368996d3543f76b9345cf227"
    static let enabledFeatures = "native-skia"
}
