// Generated by scripts/update-rhwp-core-build-info.sh. Do not edit manually.
enum RhwpCoreBuildInfo {
    static let releaseTag = "v0.8.7"
    static let commit = "1a76570e833917d15817415a53c09ad61ab3203f"
    static let enabledFeatures = "native-skia"
}
